---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Restrictions connues dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions liées à Cloud Volumes ONTAP dans tous les fournisseurs de cloud"].



== Limites de l'utilisation des extensions de machines virtuelles Azure

Dans un déploiement, Cloud Volumes ONTAP ne prend pas en charge les extensions de machines virtuelles et les applications de machines virtuelles Azure. L'utilisation d'Cloud Volumes ONTAP dans Azure avec des extensions de machine virtuelle entraîne des retards dans les opérations, et NetApp recommande de les éviter.



== Limites de Flash cache

Cloud Volumes ONTAP utilise le stockage NVMe local dans certains types de machines virtuelles, comme _Flash cache_. Notez cette limitation :

* Le réchauffage du cache après un redémarrage n'est pas pris en charge.




== Limitations de LA HAUTE DISPONIBILITÉ

Les paires HAUTE DISPONIBILITÉ ne sont pas prises en charge dans certaines régions.

https://cloud.netapp.com/cloud-volumes-global-regions["Affichez la liste des régions Azure prises en charge"^].
