---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: Azure prend en charge plusieurs configurations Cloud Volumes ONTAP. 
---
= Configurations prises en charge pour Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure prend en charge plusieurs configurations Cloud Volumes ONTAP.



== Configurations prises en charge par licence

Cloud Volumes ONTAP est disponible dans Azure en tant que système à un seul nœud et en tant que paire de nœuds haute disponibilité pour la tolérance aux pannes et la continuité de l'activité.

La mise à niveau d'un système à un seul nœud vers une paire haute disponibilité n'est pas prise en charge. Si vous souhaitez passer d'un système à un seul nœud à une paire haute disponibilité, vous devez déployer un nouveau système et répliquer les données du système existant vers le nouveau.

Cloud Volumes ONTAP peut être exécuté sur une instance de machine virtuelle réservée ou à la demande auprès de votre fournisseur cloud. Les solutions qui utilisent d'autres types d'instances VM ne sont pas prises en charge.

Pour les spécifications des instances prises en charge, reportez-vous au  https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/overview["Documentation Microsoft Azure"^] .



=== Systèmes à un seul nœud

Lorsque vous déployez Cloud Volumes ONTAP en tant que système à un seul nœud dans Azure, vous avez le choix entre plusieurs configurations de licence basées sur la capacité ou sur les nœuds.

Cloud Volumes ONTAP peut être exécuté sur une instance de machine virtuelle réservée ou à la demande auprès de votre fournisseur cloud. Les solutions qui utilisent d'autres types d'instances VM ne sont pas prises en charge.

[role="tabbed-block"]
====
.Licences basées sur la capacité
--
[cols="h,d,d,d"]
|===
|  | Fréemium | Optimisé ^5^ | Licence basée sur la capacité (Essentials et Professional) 


| Capacité système maximale (disques + stockage objet) | 500 Gio  a| 
Avec des licences basées sur la capacité, chaque système Cloud Volumes ONTAP prend en charge la hiérarchisation du stockage d'objets.  La capacité totale à plusieurs niveaux peut évoluer jusqu'à la limite de compartiment du fournisseur de cloud.  Bien que la licence n'impose pas de restrictions de capacité, vous devez suivre les https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Bonnes pratiques de FabricPool"^] pour garantir des performances, une fiabilité et une rentabilité optimales lors de la configuration et de la gestion de la hiérarchisation.



| Types de machines virtuelles pris en charge  a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4
* E8ds_v4
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^

 a| 
* DS4_v2 ^1^
* DS13_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E4ds_v5
* E8ds_v5

 a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Types de disque pris en charge ^4^ 3+| Disques gérés HDD standard, disques gérés SSD standard, disques gérés SSD premium et disques gérés SSD v2 Premium. 
|===
Remarques :

. ^1^ les familles de machines DS_v2 et es_v3 ne peuvent plus être sélectionnées sur BlueXP  lors du déploiement de nouvelles instances de Cloud Volumes ONTAP dans Azure. Ces familles seront conservées et prises en charge uniquement dans les anciens systèmes existants. Les nouveaux déploiements de Cloud Volumes ONTAP sont pris en charge dans Azure uniquement à partir de la version 9.12.1. Nous vous recommandons de passer à es_v4 ou à toute autre série compatible avec Cloud Volumes ONTAP 9.12.1 et versions ultérieures. Les machines des séries DS_v2 et es_v3, cependant, seront disponibles pour les nouveaux déploiements effectués via l'API.
. ^2^ ce type de machine virtuelle inclut le stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash cache_. Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Elle est efficace pour les charges de travail aléatoires exigeantes en lecture, notamment les bases de données, la messagerie et les services de fichiers. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["En savoir plus >>"^].
+
La version minimale de ONTAP requise pour la configuration de Flash cache sur Azure est la version 9.13.1 GA.

. ^3^ ces types de machines virtuelles utilisent un https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["SSD Ultra"^] pour VNVRAM, ce qui assure de meilleures performances d'écriture.
+
Si vous choisissez l'un de ces types de VM lorsque vous déployez un nouveau système Cloud Volumes ONTAP, vous ne pouvez pas passer à un autre type de VM qui _n'utilise pas_ un SSD Ultra pour VNVRAM. Par exemple, vous ne pouvez pas passer de E8ds_v4 à E8s_v3, mais vous pouvez passer de E8ds_v4 à E32ds_v4 car ces deux types de VM utilisent des SSD Ultra. De même, lorsque vous déployez un nouveau système Cloud Volumes ONTAP, vous ne pouvez pas modifier le type de machine virtuelle en un type qui ne prend pas en charge les disques gérés SSD v2 Premium. Pour en savoir plus sur les configurations prises en charge pour les disques gérés SSD v2 Premium, reportez-vous à https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Configuration à zone de disponibilité unique HAUTE DISPONIBILITÉ avec disques gérés partagés"^]la section.

+
Inversement, si vous avez déployé Cloud Volumes ONTAP à l'aide d'un autre type de VM, vous ne pourrez pas passer à un type de VM utilisant un SSD Ultra pour VNVRAM. Par exemple, vous ne pouvez pas passer de E8s_v3 à E8ds_v4.

. ^4^ Pour plus d'informations sur les types de disques pris en charge dans les déploiements à nœud unique, reportez-vous à  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-single-node["Azure (un seul nœud)"^] . Lors de l'utilisation d'un système à un seul nœud, la vitesse d'écriture élevée est prise en charge avec tous les types d'instances. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^]. Les performances d'écriture améliorées sont activées lorsque l'utilisation de disques SSD est utilisée.
. ^5^ À compter du 11 août 2025, la licence Cloud Volumes ONTAP Optimized est obsolète et ne sera plus disponible à l'achat ou au renouvellement sur la place de marché Azure pour les abonnements à la carte (PAYGO). Pour plus d'informations, consultez  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Fin de disponibilité des licences optimisées"^] .


--
.Licences basées sur les nœuds
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAIEMENT À L'UTILISATION Standard | PAIEMENT À L'UTILISATION Premium | BYOL basé sur les nœuds 


| Capacité système maximale (disques + stockage objet) | 2 Tio ^5^ | 10 To | 368 To | 368 Tio par licence 


| Types de machines virtuelles pris en charge  a| 
* E4s_v3 ^1^
* E4ds_v4 ^3^
* E4ds_v5

 a| 
* DS4_v2 ^1^
* DS13_v2 ^1^
* E8s_v3 ^1^
* E8ds_v4 ^3^
* E8ds_v5
* L8S_v3 ^2^

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^

 a| 
* DS4_v2 ^1^
* DS5_v2 ^1^
* DS13_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3 ^1^
* E8s_v3 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Types de disque pris en charge ^4^ 4+| Disques gérés HDD standard, disques gérés SSD standard et disques gérés SSD premium 
|===
Remarques :

. ^1^ les familles de machines DS_v2 et es_v3 ne peuvent plus être sélectionnées sur BlueXP  lors du déploiement de nouvelles instances de Cloud Volumes ONTAP dans Azure. Ces familles seront conservées et prises en charge uniquement dans les anciens systèmes existants. Les nouveaux déploiements de Cloud Volumes ONTAP sont pris en charge dans Azure uniquement à partir de la version 9.12.1. Nous vous recommandons de passer à es_v4 ou à toute autre série compatible avec Cloud Volumes ONTAP 9.12.1 et versions ultérieures. Les machines des séries DS_v2 et es_v3, cependant, seront disponibles pour les nouveaux déploiements effectués via l'API.
. ^2^ ce type de machine virtuelle inclut le stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash cache_. Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Elle est efficace pour les charges de travail aléatoires exigeantes en lecture, notamment les bases de données, la messagerie et les services de fichiers. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["En savoir plus >>"^].
. ^3^ ces types de machines virtuelles utilisent un https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["SSD Ultra"^] pour VNVRAM, ce qui assure de meilleures performances d'écriture.
+
Si vous choisissez l'un de ces types de VM lorsque vous déployez un nouveau système Cloud Volumes ONTAP, vous ne pouvez pas passer à un autre type de VM qui _n'utilise pas_ un SSD Ultra pour VNVRAM. Par exemple, vous ne pouvez pas passer de E8ds_v4 à E8s_v3, mais vous pouvez passer de E8ds_v4 à E32ds_v4 car ces deux types de VM utilisent des SSD Ultra.

+
Inversement, si vous avez déployé Cloud Volumes ONTAP à l'aide d'un autre type de VM, vous ne pourrez pas passer à un type de VM utilisant un SSD Ultra pour VNVRAM. Par exemple, vous ne pouvez pas passer de E8s_v3 à E8ds_v4.

. ^4^ la vitesse d'écriture élevée est prise en charge avec tous les types d'instances lors de l'utilisation d'un système à nœud unique. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^]. Les performances d'écriture améliorées sont activées lorsque l'utilisation de disques SSD est utilisée.
. ^5^le Tiering des données vers le stockage Azure Blob n'est pas pris en charge avec PAYGO Explore.


--
====


=== Paires HA

Lors du déploiement de Cloud Volumes ONTAP en tant que paire HA dans Azure, vous pouvez choisir l'une des configurations suivantes.



==== Paires HA avec un blob de pages

Vous pouvez utiliser les configurations suivantes avec les déploiements d'objets blob de page haute disponibilité Cloud Volumes ONTAP existants dans Azure.


NOTE: Les blobs de page Azure ne sont pris en charge par aucun nouveau déploiement.

[role="tabbed-block"]
====
.Licences basées sur la capacité
--
[cols="h,d,d,d"]
|===
|  | Fréemium | Optimisé ^4^ | Licence basée sur la capacité (Essentials et Professional) 


| Capacité système maximale (disques + stockage objet) | 500 Gio  a| 
Avec des licences basées sur la capacité, chaque système Cloud Volumes ONTAP prend en charge la hiérarchisation du stockage d'objets.  La capacité totale à plusieurs niveaux peut évoluer jusqu'à la limite de compartiment du fournisseur de cloud.  Bien que la licence n'impose pas de restrictions de capacité, vous devez suivre les https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Bonnes pratiques de FabricPool"^] pour garantir des performances, une fiabilité et une rentabilité optimales lors de la configuration et de la gestion de la hiérarchisation.



| Types de machines virtuelles pris en charge  a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Types de disques pris en charge 3+| Blobs de page 
|===
Remarques :

. ^1^ Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec ces types de machines virtuelles lors de l'utilisation d'une paire HA. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^].
. ^2^ Cette machine virtuelle est recommandée uniquement lorsque le contrôle de maintenance Azure est nécessaire. Cette utilisation n'est pas recommandée pour les autres cas d'utilisation en raison des tarifs plus élevés.
. ^3^ Ces machines virtuelles ne sont prises en charge que dans les déploiements de Cloud Volumes ONTAP 9.11.1 ou version antérieure. Ces types de VM vous permettent de mettre à niveau un déploiement de blob de pages existant de Cloud Volumes ONTAP 9.11.1 vers 9.12.1. Vous ne pouvez pas effectuer de nouveaux déploiements de blob de page avec Cloud Volumes ONTAP 9.12.1 ou version ultérieure.
. ^4^ À compter du 11 août 2025, la licence Cloud Volumes ONTAP Optimized est obsolète et ne sera plus disponible à l'achat ou au renouvellement sur la place de marché Azure pour les abonnements à la carte (PAYGO). Pour plus d'informations, consultez  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Fin de disponibilité des licences optimisées"^] .


--
.Licences basées sur les nœuds
--
[cols="h,d,d,d"]
|===
|  | PAIEMENT À L'UTILISATION Standard | PAIEMENT À L'UTILISATION Premium | BYOL basé sur les nœuds 


| Capacité système maximale (disques + stockage objet) | 10 To | 368 To | 368 Tio par licence 


| Types de machines virtuelles pris en charge  a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E48s_v3 ^1^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Types de disques pris en charge 3+| Blobs de page 
|===
Remarques :

. ^1^ Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec ces types de machines virtuelles lors de l'utilisation d'une paire HA. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^].
. ^2^ Cette machine virtuelle est recommandée uniquement lorsque le contrôle de maintenance Azure est nécessaire. Cette utilisation n'est pas recommandée pour les autres cas d'utilisation en raison des tarifs plus élevés.
. ^3^ Ces machines virtuelles ne sont prises en charge que dans les déploiements de Cloud Volumes ONTAP 9.11.1 ou version antérieure. Ces types de VM vous permettent de mettre à niveau un déploiement de blob de pages existant de Cloud Volumes ONTAP 9.11.1 vers 9.12.1. Vous ne pouvez pas effectuer de nouveaux déploiements de blob de page avec Cloud Volumes ONTAP 9.12.1 ou version ultérieure.


--
====


==== Paires HAUTE DISPONIBILITÉ avec disques gérés partagés

Lors du déploiement de Cloud Volumes ONTAP en tant que paire HA dans Azure, vous pouvez choisir l'une des configurations suivantes.

[role="tabbed-block"]
====
.Licences basées sur la capacité
--
[cols="h,d,d,d"]
|===
|  | Fréemium | Optimisé ^7^ | Licence basée sur la capacité (Essentials et Professional) 


| Capacité système maximale (disques + stockage objet) | 500 Gio  a| 
Avec des licences basées sur la capacité, chaque système Cloud Volumes ONTAP prend en charge la hiérarchisation du stockage d'objets.  La capacité totale à plusieurs niveaux peut évoluer jusqu'à la limite de compartiment du fournisseur de cloud.  Bien que la licence n'impose pas de restrictions de capacité, vous devez suivre les https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Bonnes pratiques de FabricPool"^] pour garantir des performances, une fiabilité et une rentabilité optimales lors de la configuration et de la gestion de la hiérarchisation.



| Types de machines virtuelles pris en charge  a| 
* E8ds_v4
* E32ds_v4 ^1^
* E48ds_v4 ^1^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3,5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3,5^
* L64s_v3 ^1,3,5^

 a| 
* E8ds_v4
* E8ds_v5 ^4^

 a| 
* E8ds_v4
* E32ds_v4 ^1^
* E48ds_v4 ^1^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3,5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3,5^
* L64s_v3 ^1,3,5^




| Types de disque pris en charge ^6^ 3+| Disques gérés HDD standard, disques gérés SSD standard, disques gérés SSD premium et disques gérés SSD v2 Premium. 
|===
Remarques :

. ^1^ Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec ces types de machines virtuelles lors de l'utilisation d'une paire HA. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^].
. ^2^ Cette machine virtuelle est recommandée uniquement lorsque le contrôle de maintenance Azure est nécessaire. Cette utilisation n'est pas recommandée pour les autres cas d'utilisation en raison des tarifs plus élevés.
. ^3^ La prise en charge de plusieurs zones de disponibilité démarre à partir de la version 9.13.1 ONTAP .
. ^4^ La prise en charge de plusieurs zones de disponibilité démarre à partir de la version ONTAP 9.14.1 RC1.
. ^5^ Ce type de machine virtuelle inclut un stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash Cache_. Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Elle est efficace pour les charges de travail aléatoires exigeantes en lecture, notamment les bases de données, la messagerie et les services de fichiers. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["En savoir plus >>"^].
. ^6^ Pour plus d'informations sur les types de disques pris en charge pour les déploiements HA dans des zones de disponibilité uniques et multiples, reportez-vous à  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-ha-pair["Azure (paire HA)"^] .
. ^7^ À compter du 11 août 2025, la licence Cloud Volumes ONTAP Optimized est obsolète et ne sera plus disponible à l'achat ou au renouvellement sur la place de marché Azure pour les abonnements à la carte (PAYGO). Pour plus d'informations, consultez  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Nouveautés de Cloud Volumes ONTAP"^] .


--
.Licences basées sur les nœuds
--
[cols="h,d,d,d"]
|===
|  | PAIEMENT À L'UTILISATION Standard | PAIEMENT À L'UTILISATION Premium | BYOL basé sur les nœuds 


| Capacité système maximale (disques + stockage objet) | 10 To | 368 To | 368 Tio par licence 


| Types de machines virtuelles pris en charge  a| 
* E8ds_v4 ^4^
* E8ds_v5
* L8s_v3 ^4,5^

 a| 
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4,5^
* L64s_v3 ^1,4,5^

 a| 
* E8ds_v4 ^4^
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4,5^
* L64s_v3 ^1,4,5^




| Types de disques pris en charge 3+| Disques gérés 
|===
Remarques :

. ^1^ Cloud Volumes ONTAP prend en charge une vitesse d'écriture élevée avec ces types de machines virtuelles lors de l'utilisation d'une paire HA. Vous pouvez augmenter la vitesse d'écriture à partir de BlueXP  pendant le déploiement ou à tout moment après. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["En savoir plus sur le choix d'une vitesse d'écriture"^].
. ^2^ Cette machine virtuelle est recommandée uniquement lorsque le contrôle de maintenance Azure est nécessaire. Cette utilisation n'est pas recommandée pour les autres cas d'utilisation en raison des tarifs plus élevés.
. ^3^ Ces types de machines virtuelles ne sont pris en charge que pour les paires HA dans une configuration de zone de disponibilité unique exécutée sur des disques gérés partagés.
. ^4^ Ces types de machines virtuelles sont pris en charge pour les paires HA dans les configurations de zone de disponibilité unique et de zone de disponibilité multiple exécutées sur des disques gérés partagés. Pour les types de VM LS_v3, la prise en charge de plusieurs zones de disponibilité commence à partir de la version 9.13.1 de ONTAP. Pour les types de VM Eds_v5, la prise en charge de plusieurs zones de disponibilité commence à partir de ONTAP version 9.14.1 RC1.
. ^5^ Ce type de machine virtuelle inclut un stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash Cache_. Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Elle est efficace pour les charges de travail aléatoires exigeantes en lecture, notamment les bases de données, la messagerie et les services de fichiers. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["En savoir plus >>"^].


--
====


== Tailles de disque prises en charge

Dans Azure, un agrégat peut contenir jusqu'à 12 disques de même type et de même taille.



=== Systèmes à un seul nœud

Les systèmes à un seul nœud utilisent des disques gérés Azure. Les tailles de disque suivantes sont prises en charge :

[cols="3*"]
|===
| SSD premium | SSD standard | Disque dur standard 


 a| 
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To

 a| 
* 100 Gio
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To

 a| 
* 100 Gio
* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 To
* 32 To


|===


=== Paires HA

Les paires HAUTE DISPONIBILITÉ utilisent des disques gérés Azure. Les types et tailles de disques suivants sont pris en charge.

(Les blobs pages sont pris en charge avec les paires haute disponibilité déployées avant la version 9.12.1.)

*SSD Premium*

* 500 Gio
* 1 To
* 2 To
* 4 To
* 8 To
* 16 Tio (disques gérés uniquement)
* 32 Tio (disques gérés uniquement)




== Régions prises en charge

Pour la prise en charge des régions Azure, voir https://bluexp.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"^].
