---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.19.1 inclut une nouvelle amélioration. 
---
= Nouveautés de Cloud Volumes ONTAP 9.19.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez désormais déployer et mettre à niveau vers Cloud Volumes ONTAP 9.19.1. Vous pouvez consulter la version de base de cette version ainsi que les dernières versions de correctifs disponibles pour le déploiement et la mise à niveau dans la Console.

Pour en savoir plus sur les fonctionnalités de Cloud Volumes ONTAP, les configurations prises en charge, les limites et plus encore, consultez https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Documentation Cloud Volumes ONTAP"^].



[[9-19-1-rc-13-july-2026]]
== 9.19.1 RC (13 juillet 2026)

La version candidate (RC) 9.19.1 de Cloud Volumes ONTAP est désormais disponible pour le déploiement et la mise à niveau uniquement sur Google Cloud. Cette version n'est pas disponible pour le déploiement et la mise à niveau sur Amazon Web Services (AWS) ni sur Microsoft Azure (Azure).



[[upgrade-notes]]
== Notes de mise à niveau

Lisez ces notes pour en savoir plus sur la mise à niveau vers cette version.



[[how-to-upgrade]]
=== Comment mettre à niveau

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis la console. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l’aide de System Manager ou de l’interface de ligne de commande. Cela peut avoir un impact sur la stabilité du système.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer une mise à niveau lorsque la console vous avertit"^] .



[[supported-upgrade-path]]
=== Chemin de mise à niveau pris en charge

La mise à niveau vers Cloud Volumes ONTAP 9.19.1 RC depuis la version 9.18.1 est possible uniquement sur Google Cloud. La console vous invitera à mettre à niveau les systèmes Cloud Volumes ONTAP éligibles vers cette version.


NOTE: Sur AWS et Azure, vous ne serez pas invité à effectuer une mise à niveau vers la version 9.19.1 RC, car cette version n'est pas disponible pour le déploiement et la mise à niveau pour ces fournisseurs de cloud.



[[downtime]]
=== Ou non

* La mise à niveau d'un système à nœud unique met le système hors ligne pendant une durée maximale de 25 minutes, durant laquelle les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité ne perturbe pas les opérations et les E/S sont interrompues. Lors de cette mise à niveau sans interruption, chaque nœud est mis à niveau en tandem pour continuer à assurer le service d'E/S aux clients.

