---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Limitations connues de Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions liées à Cloud Volumes ONTAP dans tous les fournisseurs de cloud"].



== Limites de l'utilisation des extensions de machines virtuelles Azure

Cloud Volumes ONTAP ne prend pas en charge les extensions de machine virtuelle (VM) Azure, car elles affectent les opérations de gestion BlueXP .  Lors du déploiement, BlueXP empêche l’installation de toute extension sur vos machines virtuelles.  Si des extensions sont déjà installées sur vos machines virtuelles Cloud Volumes ONTAP existantes, contactez le support Microsoft Azure pour les supprimer.  Pour obtenir des conseils, reportez-vous à l'article de la base de connaissances (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Les extensions de gestion des machines virtuelles Azure peuvent-elles être installées dans Cloud Volume ONTAP?"^]

À partir du 14 juillet 2025, NetApp enverra des e-mails et vous avertira dans BlueXP si des extensions de machine virtuelle sont détectées sur vos machines virtuelles Cloud Volumes ONTAP .



== Limitations des disques SSD Premium v2 pour les configurations HA

Les disques gérés SSD Premium v2 présentent les limitations suivantes pour les déploiements à haute disponibilité (HA) dans Azure :

* Non pris en charge dans les déploiements HA dans les régions non zonales.
* Non pris en charge dans les déploiements HA sur plusieurs zones de disponibilité.
* Uniquement pris en charge dans les configurations HA déployées dans des zones de disponibilité uniques.


Pour utiliser les disques gérés Premium SSD v2 avec les configurations Cloud Volumes ONTAP HA, assurez-vous que les exigences suivantes sont remplies :

* La version de Cloud Volumes ONTAP est 9.15.1 ou ultérieure.
* Le déploiement HA s’effectue dans une zone de disponibilité unique Azure.
* Les régions et zones sélectionnées prennent en charge les disques gérés Premium SSD v2.  Pour plus d'informations sur les régions prises en charge, reportez-vous à la https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Site Web Microsoft Azure : produits disponibles par région"^] .


Pour plus d'informations, consultez  https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Prise en charge des disques gérés SSD Premium v2 dans Azure"^] .



== Limitations liées aux déploiements haute disponibilité dans les zones de disponibilité uniques

À partir de Cloud Volumes ONTAP 9.15.1, vous pouvez déployer des instances de machine virtuelle (VM) en mode HA dans des zones de disponibilité uniques (AZ) dans Azure. Pour plus d'informations sur les critères prenant en charge cette fonctionnalité, reportez-vous à https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["Déployez des paires haute disponibilité dans des zones de disponibilité uniques dans Azure"^] .

Si la version Cloud Volumes ONTAP est antérieure à la version 9.15.1 ou si l'une de ces conditions n'est pas remplie, le modèle de déploiement précédent utilisant les jeux de disponibilité prend effet. Cela s'applique uniquement aux configurations haute disponibilité.



== Limites de Flash cache

Cloud Volumes ONTAP utilise le stockage NVMe local dans certains types de machines virtuelles, comme _Flash cache_. Notez cette limitation :

* Le réchauffage du cache après un redémarrage n'est pas pris en charge.




== Limitations des déploiements HA

Les paires HA ne sont pas prises en charge dans certaines régions.

https://bluexp.netapp.com/cloud-volumes-global-regions["Affichez la liste des régions Azure prises en charge"^].
