---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Restrictions connues dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions liées à Cloud Volumes ONTAP dans tous les fournisseurs de cloud"].



== Limites de Flash cache

Certains types de VM incluent le stockage NVMe local, que Cloud Volumes ONTAP utilise _Flash cache_. Notez les limitations suivantes pour Flash cache :

* La compression doit être désactivée sur tous les volumes pour bénéficier des améliorations de performances de Flash cache jusqu'à Cloud Volumes ONTAP 9.12.0. Lorsque vous déployez ou mettez à niveau votre système vers Cloud Volumes ONTAP 9.12.1, vous n'avez pas besoin de désactiver la compression.
+
Vous pouvez choisir l'absence d'efficacité du stockage lors de la création d'un volume depuis BlueXP, ou vous pouvez créer un volume puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].

* La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.




== Limitations de LA HAUTE DISPONIBILITÉ

Les paires HAUTE DISPONIBILITÉ ne sont pas prises en charge dans certaines régions.

https://cloud.netapp.com/cloud-volumes-global-regions["Affichez la liste des régions Azure prises en charge"^].
