---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limitations connues de Cloud Volumes ONTAP chez tous les fournisseurs cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.

Cloud Volumes ONTAP s'applique à tous les fournisseurs cloud : AWS, Azure et Google Cloud.



== Fonctions ONTAP non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge par Cloud Volumes ONTAP :

* Déduplication à la volée au niveau des agrégats
* La déduplication en arrière-plan au niveau de l'agrégat
* Centre de maintenance du disque
* Nettoyage de disque
* Mise en miroir FabricPool
* Fibre Channel (FC)
* Pools Flash
* Infinite volumes
* Groupes d'interface
* Le basculement LIF monomode d'un cluster
* MetroCluster
* Vérification multi-administrateurs
+
L'activation de la vérification multi-administration sur Cloud Volumes ONTAP entraîne une configuration non prise en charge.

* RAID4, RAID-DP, RAID-TEC (RAID0 PRIS EN CHARGE)
* Le processeur de service
* Modes SnapLock Compliance et Enterprise (seul le mode WORM cloud est pris en charge)
* SnapMirror synchrone
* VLAN
* Disponibilité continue des PME (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Actions PME disponibles en continu"^] pour les opérations non perturbatrices ne sont pas prises en charge.





== Nombre maximal d'opérations de réplication simultanées

Le nombre maximal de transferts SnapMirror ou SnapVault simultanés pour Cloud Volumes ONTAP est de 100 par nœud, indépendamment du type d'instance ou du type d'ordinateur.



== Les snapshots des fournisseurs cloud ne doivent pas être utilisés dans vos plans de sauvegarde et de restauration

Vous ne devez pas utiliser les copies Snapshot de votre fournisseur cloud dans le cadre de votre plan de sauvegarde et de restauration des données Cloud Volumes ONTAP. Utilisez toujours des copies Snapshot ONTAP ou des solutions de sauvegarde tierces pour sauvegarder et restaurer les données hébergées sur Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Découvrez comment utiliser NetApp Backup and Recovery pour sauvegarder et restaurer les données ONTAP"^] .


NOTE: Les points de cohérence ONTAP dans le système de fichiers WAFL déterminent la cohérence des données. Seul ONTAP peut suspendre le système de fichiers WAFL pour assurer une sauvegarde cohérente après panne.



== Cloud Volumes ONTAP prend uniquement en charge les instances de VM réservées et à la demande

Cloud Volumes ONTAP peut être exécuté sur une instance de machine virtuelle réservée ou à la demande auprès de votre fournisseur cloud. Les autres types d'instances de VM ne sont pas pris en charge.



== Les solutions de gestion automatique des ressources applicatives ne doivent pas être utilisées

Les solutions automatiques de gestion des ressources applicatives ne doivent pas gérer les systèmes Cloud Volumes ONTAP. Cela peut entraîner une modification de la configuration non prise en charge. Par exemple, la solution peut remplacer Cloud Volumes ONTAP par un type d'instance de machine virtuelle non pris en charge.



== Les mises à jour logicielles doivent être effectuées par la console NetApp

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées à partir de la console NetApp . Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l’aide de System Manager ou de l’interface de ligne de commande. Cela peut avoir un impact sur la stabilité du système.



== Le déploiement Cloud Volumes ONTAP ne doit pas être modifié depuis la console de votre fournisseur cloud

Les modifications apportées à une configuration Cloud Volumes ONTAP à partir de la console de votre fournisseur de cloud entraînent une configuration non prise en charge. Toute modification apportée aux ressources Cloud Volumes ONTAP que la console crée et gère peut avoir un impact sur la stabilité du système et sur la capacité de la console à gérer le système.


NOTE: Après le déploiement initial, la modification du nom d'abonnement Azure utilisé pour les ressources Cloud Volumes ONTAP est prise en charge.



== Les disques et les agrégats doivent être gérés à partir de la console

Tous les disques et agrégats doivent être créés et supprimés directement depuis la console. Vous ne devez pas effectuer ces actions à partir d’un autre outil de gestion. Cela peut avoir un impact sur la stabilité du système, entraver la possibilité d’ajouter des disques à l’avenir et potentiellement générer des frais de fournisseur de cloud redondants.



== Limitation des licences SnapManager

Les licences SnapManager par serveur sont prises en charge par Cloud Volumes ONTAP. Les licences par système de stockage (suite SnapManager) ne sont pas prises en charge.



== Limitations avec les agents et les extensions tiers

Les agents tiers et les extensions de machine virtuelle ne sont pas pris en charge sur les instances de machine virtuelle Cloud Volumes ONTAP.
