---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: Cette page décrit comment NetApp travaille avec les fournisseurs cloud pour résoudre les problèmes potentiels. 
---
= Collaboration avec des fournisseurs de cloud pour Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez comment NetApp collabore avec les fournisseurs cloud pour résoudre les problèmes potentiels.



== Bonnes pratiques de support collaboratif

NetApp s'engage à fournir au Titulaire de Licence un support technique afin de mettre en œuvre tous les efforts commercialement raisonnables pour résoudre les problèmes de support technique de Cloud Volumes ONTAP lorsqu'ils sont signalés par le Titulaire de Licence. NetApp et le fournisseur de cloud concerné ne disposent d'aucune obligation de support direct concernant les logiciels ou l'infrastructure sous licence de l'autre fournisseur.

NetApp a mis en place des outils visant à établir des relations avec les fournisseurs clouds en vigueur sur les problèmes techniques des clients susceptibles d'être liés aux services du fournisseur cloud concerné. Cependant, La meilleure façon de maintenir un flux de support transparent consiste à (i) maintenir un contrat de support en cours avec NetApp et le fournisseur cloud concerné, et (ii) coordonner des réunions de réaffectation communes avec NetApp et le fournisseur cloud en cas de problème technique et en cas de clarté du besoin sur quels produits ou services sont à l'origine de ces problèmes techniques.



== Événements de maintenance Azure

Microsoft planifie et annonce par programmation les événements de maintenance sur son infrastructure Azure VM (Virtual machine) qui peuvent affecter les machines virtuelles Cloud Volumes ONTAP. Ces événements sont annoncés 15 minutes avant la fenêtre de maintenance.

La gestion spéciale des événements de maintenance est prise en charge pour les paires haute disponibilité Cloud Volumes ONTAP. Afin de préserver l'intégrité des applications, nous procédons à un basculement préventif qui donne la priorité à la stabilité, car toute perte de connectivité de plus de 15 secondes désactive les fonctionnalités de basculement.

Lorsque la fenêtre de maintenance est annoncée, le nœud partenaire du nœud ciblé effectue un basculement. Une fois la maintenance terminée, un rétablissement est lancé. Après le retour, la paire HA est censée revenir à un état sain. Le cas échéant, contactez le support NetApp pour obtenir de l'aide. Notez que les événements de maintenance sont ciblés sur l'une des machines virtuelles d'une paire haute disponibilité à la fois, et en général, les deux nœuds sont ciblés dans un délai relativement court.

Les clients CIFS/SMB utilisant des partages CIFS Cloud Volumes ONTAP non disponibles en continu subiront une perte de session lors d'une prise de contrôle et lors du retour de l'agrégat utilisé par la session à son nœud d'origine. Il s'agit d'une limitation imposée par le protocole CIFS/SMB lui-même. Vous pouvez utiliser des produits tiers approuvés pour éviter les problèmes liés à la prise de contrôle et à la restitution. Pour obtenir de l'aide, contactez le support NetApp .


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Actions PME disponibles en continu"^] pour les opérations non perturbatrices ne sont pas prises en charge dans Cloud Volumes ONTAP.
