---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. 
---
= Limitations connues de Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Microsoft Azure. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions liées à Cloud Volumes ONTAP dans tous les fournisseurs de cloud"].



== Limites de l'utilisation des extensions de machines virtuelles Azure

Cloud Volumes ONTAP ne prend pas en charge les extensions de machines virtuelles Azure, car elles affectent les opérations de gestion BlueXP . Lors du déploiement, BlueXP empêche l'installation de toute extension sur vos machines virtuelles. Si des extensions sont déjà installées sur vos machines virtuelles Cloud Volumes ONTAP existantes, NetApp vous recommande vivement de contacter le support Microsoft Azure pour les supprimer.

À partir du 14 juillet 2025, NetApp vous avertira dans BlueXP et enverra des e-mails si des extensions de VM sont détectées sur vos VM Cloud Volumes ONTAP .



== Limites de Flash cache

Cloud Volumes ONTAP utilise le stockage NVMe local dans certains types de machines virtuelles, comme _Flash cache_. Notez cette limitation :

* Le réchauffage du cache après un redémarrage n'est pas pris en charge.




== Limites des déploiements haute disponibilité

Les paires haute disponibilité ne sont pas prises en charge dans certaines régions.

https://bluexp.netapp.com/cloud-volumes-global-regions["Affichez la liste des régions Azure prises en charge"^].



== Limitations liées aux déploiements haute disponibilité dans les zones de disponibilité uniques

À partir de la version Cloud Volumes ONTAP 9.15.1, vous pouvez déployer des instances de machine virtuelle (VM) en mode HA dans des zones de disponibilité uniques (AZ) dans Azure. Pour plus d'informations sur les critères prenant en charge cette fonction, reportez-vous à la section https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Déployez des paires haute disponibilité dans des zones de disponibilité uniques dans Azure"^].

Si la version Cloud Volumes ONTAP est antérieure à la version 9.15.1 ou si l'une de ces conditions n'est pas remplie, le modèle de déploiement précédent utilisant les jeux de disponibilité prend effet. Cela s'applique uniquement aux configurations haute disponibilité.
