---
sidebar: sidebar 
permalink: reference-limitations-gcp.html 
keywords: limitations, google cloud platform, gcp, psc, private service connect 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limitations connues de Cloud Volumes ONTAP dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Google Cloud Platform. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions liées à Cloud Volumes ONTAP dans tous les fournisseurs de cloud"].



== Limitation avec la mise en miroir des paquets

https://cloud.google.com/vpc/docs/packet-mirroring["Mise en miroir de paquets"^] Doit être désactivé dans le VPC Google Cloud dans lequel vous déployez Cloud Volumes ONTAP.

Cloud Volumes ONTAP ne peut pas fonctionner correctement si la mise en miroir des paquets est activée.



== Limitations de Google Private Service Connect

Si vous utilisez un effet de levier https://cloud.google.com/vpc/docs/private-service-connect["Google Private Service Connect"^] au sein du VPC dans lequel vous déployez Cloud Volumes ONTAP , vous devrez implémenter des enregistrements DNS qui transfèrent le trafic vers le serveur requis. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Points de terminaison de l'API"^] .

Le Tiering des données d'Cloud Volumes ONTAP dans un compartiment Google Cloud Storage n'est pas pris en charge actuellement avec Private Service Connect.
