---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.18.1 inclut une nouvelle amélioration. 
---
= Nouveautés de Cloud Volumes ONTAP 9.18.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez désormais déployer et mettre à niveau vers Cloud Volumes ONTAP 9.18.1. Vous pouvez voir la version de base de cette version et les dernières versions de correctifs disponibles pour le déploiement et la mise à niveau dans la Console.

Pour en savoir plus sur les fonctionnalités de Cloud Volumes ONTAP introduites dans les dernières versions de la NetApp Console, consultez les nouveautés dans https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^].



== 9.18.1 P1 (31 mars 2026)

Le correctif Cloud Volumes ONTAP 9.18.1 P1 est désormais disponible pour le déploiement et la mise à niveau sur AWS, Azure et Google Cloud. La Console vous invitera à mettre à niveau vos systèmes existants vers ce correctif.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.18.1P1["Consultez la liste des bugs corrigés dans le patch P1"^] (NetApp Connexion au site d'assistance requise).



== 9.18.1 GA (10 février 2026)

La version Cloud Volumes ONTAP 9.18.1 à disponibilité générale est désormais disponible pour le déploiement et la mise à niveau sur Amazon Web Services (AWS), Microsoft Azure et Google Cloud.



== Notes de mise à niveau

Lisez ces notes pour en savoir plus sur la mise à niveau vers cette version.



=== Comment mettre à niveau

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis la console. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l’aide de System Manager ou de l’interface de ligne de commande. Cela peut avoir un impact sur la stabilité du système.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer une mise à niveau lorsque la console vous avertit"^] .



=== Chemin de mise à niveau pris en charge

Vous pouvez mettre à niveau vers Cloud Volumes ONTAP 9.18.1 à partir de la version 9.17.1 P1 et des correctifs ultérieurs sur AWS, Azure et Google Cloud. La Console vous invitera à mettre à niveau les systèmes Cloud Volumes ONTAP éligibles vers cette version.



=== Ou non

* La mise à niveau d'un système à nœud unique met le système hors ligne pendant une durée maximale de 25 minutes, durant laquelle les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité ne perturbe pas les opérations et les E/S sont interrompues. Lors de cette mise à niveau sans interruption, chaque nœud est mis à niveau en tandem pour continuer à assurer le service d'E/S aux clients.

