---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1 inclut une nouvelle amélioration. 
---
= Nouveautés de Cloud Volumes ONTAP 9.12.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1 comprend de nouvelles améliorations.

D'autres fonctionnalités et améliorations sont également introduites dans les dernières versions de BlueXP (anciennement Cloud Manager). Voir la https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notes de mise à jour BlueXP"^] pour plus d'informations.



== 9.12.1 RC1 (8 décembre 2022)

Cloud Volumes ONTAP 9.12.1 Release candidate 1 est à présent disponible dans AWS, Azure et Google Cloud. Cette version comprend de nouvelles fonctionnalités et améliorations suivantes.



=== Licence ONTAP S3 dans GCP

Une licence ONTAP S3 est désormais incluse sur les systèmes Cloud Volumes ONTAP nouveaux et existants qui exécutent la version 9.12.1 ou une version ultérieure dans Google Cloud Platform.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Découvrez comment configurer et gérer les services de stockage objet S3 dans ONTAP"^]



=== Prise en charge NVMe-TCP dans Cloud Volumes ONTAP

Le protocole NVMe-TCP est pris en charge par les fournisseurs cloud si vous utilisez Cloud Volumes ONTAP version 9.12.1 ou ultérieure. BlueXP ne propose pas de fonctionnalités de gestion pour NVMe-TCP.

Pour plus d'informations sur la configuration de NVMe via ONTAP, reportez-vous à la section link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Configuration d'une VM de stockage pour NVMe"^].



=== Azure HA dans une zone de disponibilité unique avec disques gérés partagés

Vous pouvez désormais déployer une configuration Cloud Volumes ONTAP HA en utilisant le stockage redondant local Microsoft Azure (LRS) exécuté sur des disques gérés partagés. Le stockage redondant local réplique vos données trois fois au sein d'un data Center unique dans la même région.

Pour plus d'informations sur l'architecture de configuration haute disponibilité et ses composants, voir link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Paires haute disponibilité dans Azure"^].

Lorsque vous déployez une nouvelle paire haute disponibilité dans Azure dans une seule zone de disponibilité, vous utiliserez maintenant des disques gérés partagés LRS plutôt que des blobs de page pour le stockage. Il n'y a pas de changement à l'assistant de l'environnement de travail. Pour utiliser cette nouvelle configuration, il vous suffit de choisir une seule zone de disponibilité. Pour plus de détails, voir link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Lancement d'une paire HA Cloud Volumes ONTAP dans Azure"^].



=== Azure HA dans plusieurs zones de disponibilité avec disques gérés partagés

Vous pouvez désormais déployer une configuration Cloud Volumes ONTAP HA en utilisant Azure plusieurs zones de disponibilité dans une région. La nouvelle configuration protège les données contre les défaillances de data Center et maintient la disponibilité des applications grâce à l'utilisation de disques gérés partagés ZRS (zone-redondant Storage) Azure.

Pour plus d'informations sur l'architecture de configuration haute disponibilité et ses composants, voir link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Paires haute disponibilité dans Azure"^].

Pour utiliser cette nouvelle configuration, voir link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Lancement d'une paire HA Cloud Volumes ONTAP dans Azure"^].



== Notes de mise à niveau

Lisez ces notes pour en savoir plus sur la mise à niveau vers cette version.



=== Comment mettre à niveau

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis BlueXP. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer la mise à niveau lorsque BlueXP vous avertit"^].



=== Chemin de mise à niveau pris en charge

Vous pouvez effectuer la mise à niveau vers Cloud Volumes ONTAP 9.12.1 à partir des versions 9.12.0 et 9.11.1. BlueXP vous invitera à mettre à niveau les systèmes Cloud Volumes ONTAP éligibles vers cette version.



=== Version requise du connecteur

Le connecteur BlueXP doit exécuter la version 3.9.24 ou ultérieure pour déployer de nouveaux systèmes Cloud Volumes ONTAP 9.12.1 et mettre à niveau les systèmes existants vers la version 9.12.1.


TIP: Les mises à niveau automatiques du connecteur sont activées par défaut, vous devez donc exécuter la dernière version.



=== Ou non

* La mise à niveau d'un système à un nœud unique permet de mettre le système hors ligne pendant 25 minutes au cours desquelles les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité s'effectue sans interruption et les E/S sont continues. Au cours de ce processus de mise à niveau sans interruption, chaque nœud est mis à niveau en tandem afin de continuer à traiter les E/S aux clients.




=== les instances c4, m4 et r4 ne sont plus prises en charge

Dans AWS, les types d'instances EC2 c4, m4 et r4 ne sont plus pris en charge par Cloud Volumes ONTAP. Si un système existant fonctionne sur un type d'instance c4, m4 ou r4, vous devez passer à un type d'instance dans la famille d'instances c5, m5 ou r5.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Découvrez comment modifier le type d'instance EC2 pour Cloud Volumes ONTAP"^].

Reportez-vous à la section link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Support NetApp"^] pour en savoir plus sur la fin de disponibilité et la prise en charge de ces types d'instances.
